import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Container from '../src/components/Container'
import Header from '../src/components/Header'
import Sidebar from '../src/components/Sidebar'

const Home: NextPage = () => {
  const [sidebarActive, setSidebarActive] = useState(false)
  return (
    <div className="bg-[rgb(30,30,47)] h-screen relative w-screen">
      <Head>
        <title>Sistem Terdistribusi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex'>
        <Sidebar open={sidebarActive} />
        {/* content here */}
        <div className={`flex-1 text-white ${sidebarActive ? "translate-x-72" : ""}`}>
          <Header sidebarToggle={() => setSidebarActive(!sidebarActive)} title="Product Catalog" />
          <Container>
            <section>
              Main Content
            </section>
          </Container>
        </div>
      </div>
    </div>
  )
}

export default Home
