import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../src/components/Button'

const Home: NextPage = () => {
  return (
    <div className="bg-orange-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={() => alert("surti")}>Hell you</Button>
    </div>
  )
}

export default Home
