import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

import ProductEditView from '../../src/components/ProductEditView'

const Edit: NextPage = () => {
    return (
        <>
            <Head>
                <title>Sistem Terdistribusi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductEditView />
        </>
    )
}

export default Edit