import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'

import ProductEditView from '../../../src/components/ProductEditView'
import { BASE_URL_PRODUCT_API } from '../../../utils/const'

const Edit: NextPage = ({ product }: any) => {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Sistem Terdistribusi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductEditView product={product} />
        </>
    )
}

export async function getServerSideProps(context: any) {
    const { query } = context
    const { data: result } = await axios.get(`${BASE_URL_PRODUCT_API}?master=supersecret`)
    const product = result.data.find((item: any) => item.id === Number(query.id))
    return {
        props: {
            product
        }, // will be passed to the page component as props
    }
}

export default Edit